<a href="https://colab.research.google.com/github/Sikura/Awesome-pytorch-list/blob/master/Copy_of_tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# this line is written to plot all plots just in Jupiter notebook
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [0]:
#A future statement is a directive to the compiler that a particular module should be compiled using syntax or semantics
#that will be available in a specified future release of Python. The future statement is intended to ease migration to 
#future versions of Python that introduce incompatible changes to the language. 
#It allows use of the new features on a per-module basis before the release in which the feature becomes standard.
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [0]:
x = torch.empty(5, 3)
print(x)

tensor([[1.2952e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [0]:
# create 2d uninitialized tensor
x = torch.empty(5,5)
print(x)

tensor([[1.5469e-36, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])


Construct a randomly initialized matrix:



In [0]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6759, 0.3508, 0.3688],
        [0.9381, 0.1871, 0.1332],
        [0.4403, 0.1149, 0.5960],
        [0.6812, 0.5396, 0.8056],
        [0.0883, 0.7883, 0.7852]])


In [0]:
# construct a randomly initialized matrix
x= torch.rand(2,2,2)
print(x)

tensor([[[0.6748, 0.8133],
         [0.4185, 0.4098]],

        [[0.5087, 0.1097],
         [0.4183, 0.2354]]])


Construct a matrix filled zeros and of dtype long:



In [0]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
# create a 2d tensor filled with zeros
x = torch.zeros(2, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0]])


Construct a tensor directly from data:



In [0]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
# construct a tensor from a given data
x = torch.tensor([[2,3],[4,4]])
print(x)

tensor([[2, 3],
        [4, 4]])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [0]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1736,  0.9395,  1.1659],
        [-0.2364, -0.5180,  0.1140],
        [-1.3596, -0.3700, -1.2303],
        [-0.2359, -0.1627, -0.5940],
        [-0.9474,  1.1118, -0.5712]])


In [0]:
# the following method fill the tensor with the value of 1
x = x.new_ones(5,3, dtype= torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3492,  1.5093, -1.7783],
        [-1.2693, -0.6325, -0.4237],
        [ 0.1727, -0.1796,  0.3100],
        [ 2.0566, -0.7383, -0.3705],
        [-0.3776,  0.4071,  1.3400]])


Get its size:



In [0]:
print(x.size())

torch.Size([5, 3])


In [0]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [0]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.2114,  1.5641, -1.5340],
        [-0.9156, -0.1592,  0.5311],
        [ 0.9303,  0.3389,  0.4644],
        [ 2.4402, -0.5752, -0.1967],
        [-0.3636,  0.5099,  1.8254]])


In [0]:
x = torch.rand(5,5)
print(x)
y = torch.rand(5,5)
print(y)
print(x+y)

tensor([[0.4306, 0.2418, 0.8207, 0.7851, 0.3018],
        [0.5274, 0.9280, 0.3378, 0.3264, 0.6365],
        [0.9369, 0.0282, 0.6349, 0.4914, 0.6132],
        [0.6907, 0.6588, 0.6162, 0.1098, 0.2552],
        [0.7633, 0.0600, 0.9877, 0.3414, 0.1110]])
tensor([[0.3876, 0.3393, 0.2412, 0.8692, 0.8347],
        [0.9575, 0.1948, 0.6807, 0.5115, 0.6021],
        [0.8719, 0.8715, 0.2870, 0.7275, 0.4051],
        [0.3915, 0.9951, 0.7802, 0.6611, 0.3752],
        [0.4921, 0.0543, 0.4487, 0.7122, 0.2122]])
tensor([[0.8182, 0.5811, 1.0620, 1.6543, 1.1365],
        [1.4849, 1.1228, 1.0186, 0.8379, 1.2386],
        [1.8088, 0.8997, 0.9220, 1.2188, 1.0183],
        [1.0823, 1.6539, 1.3964, 0.7709, 0.6304],
        [1.2554, 0.1143, 1.4364, 1.0535, 0.3231]])


Addition: syntax 2



In [0]:
print(torch.add(x, y))

tensor([[0.8182, 0.5811, 1.0620, 1.6543, 1.1365],
        [1.4849, 1.1228, 1.0186, 0.8379, 1.2386],
        [1.8088, 0.8997, 0.9220, 1.2188, 1.0183],
        [1.0823, 1.6539, 1.3964, 0.7709, 0.6304],
        [1.2554, 0.1143, 1.4364, 1.0535, 0.3231]])


In [0]:
print(torch.add(x,y))

tensor([[0.8182, 0.5811, 1.0620, 1.6543, 1.1365],
        [1.4849, 1.1228, 1.0186, 0.8379, 1.2386],
        [1.8088, 0.8997, 0.9220, 1.2188, 1.0183],
        [1.0823, 1.6539, 1.3964, 0.7709, 0.6304],
        [1.2554, 0.1143, 1.4364, 1.0535, 0.3231]])


Addition: providing an output tensor as argument



In [0]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[0.8182, 0.5811, 1.0620, 1.6543, 1.1365],
        [1.4849, 1.1228, 1.0186, 0.8379, 1.2386],
        [1.8088, 0.8997, 0.9220, 1.2188, 1.0183],
        [1.0823, 1.6539, 1.3964, 0.7709, 0.6304],
        [1.2554, 0.1143, 1.4364, 1.0535, 0.3231]])


In [0]:
result = torch.empty(3,3)
torch.add(x,y, out=result)
print(result)

tensor([[0.8182, 0.5811, 1.0620, 1.6543, 1.1365],
        [1.4849, 1.1228, 1.0186, 0.8379, 1.2386],
        [1.8088, 0.8997, 0.9220, 1.2188, 1.0183],
        [1.0823, 1.6539, 1.3964, 0.7709, 0.6304],
        [1.2554, 0.1143, 1.4364, 1.0535, 0.3231]])


Addition: in-place



In [0]:
# adds x to y
y.add_(x)
print(y)

tensor([[0.8182, 0.5811, 1.0620, 1.6543, 1.1365],
        [1.4849, 1.1228, 1.0186, 0.8379, 1.2386],
        [1.8088, 0.8997, 0.9220, 1.2188, 1.0183],
        [1.0823, 1.6539, 1.3964, 0.7709, 0.6304],
        [1.2554, 0.1143, 1.4364, 1.0535, 0.3231]])


In [0]:
y.add_(x)
print(y)

tensor([[1.6793, 1.0646, 2.7034, 3.2244, 1.7401],
        [2.5397, 2.9788, 1.6942, 1.4908, 2.5116],
        [3.6826, 0.9560, 2.1919, 2.2016, 2.2447],
        [2.4638, 2.9714, 2.6287, 0.9905, 1.1407],
        [2.7819, 0.2343, 3.4118, 1.7362, 0.5451]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [0]:
print(x[:, 1])

tensor([0.2418, 0.9280, 0.0282, 0.6588, 0.0600])


In [0]:
print(y[:,1])

tensor([1.0646, 2.9788, 0.9560, 2.9714, 0.2343])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [0]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [0]:
#torch view to resize and reshape tensor

z = torch.randn(4,4)
print(z)
y = z.view(16)
print(y)
x = z.view(-1, 8)
print(x)

tensor([[ 1.2071,  0.0760,  1.0486, -0.1286],
        [-1.3248,  0.4072, -1.7416,  0.3402],
        [-0.8678,  0.4277, -0.1944,  1.2515],
        [-0.2266,  0.4011,  0.7426,  0.0209]])
tensor([ 1.2071,  0.0760,  1.0486, -0.1286, -1.3248,  0.4072, -1.7416,  0.3402,
        -0.8678,  0.4277, -0.1944,  1.2515, -0.2266,  0.4011,  0.7426,  0.0209])
tensor([[ 1.2071,  0.0760,  1.0486, -0.1286, -1.3248,  0.4072, -1.7416,  0.3402],
        [-0.8678,  0.4277, -0.1944,  1.2515, -0.2266,  0.4011,  0.7426,  0.0209]])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [0]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([1.1788])
1.1787798404693604


In [0]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.9227])
-0.9227104187011719


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [0]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [0]:
a1 = torch.ones(5,5)
print(a1)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [0]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [0]:
print(a1.numpy())

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


See how the numpy array changed in value.



In [0]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


In [0]:
# making operations with a tensor also reflects on numpy array that was created from this tensor
b1 = a1.numpy()
print(b1)
print(a1)
a1.add_(1)
print(a1)
print(b1)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [0]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [0]:
import numpy as np
a  = np.ones(4)
print(a)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1.]
[2. 2. 2. 2.]
tensor([2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [0]:
print(z)

tensor([[ 1.2071,  0.0760,  1.0486, -0.1286],
        [-1.3248,  0.4072, -1.7416,  0.3402],
        [-0.8678,  0.4277, -0.1944,  1.2515],
        [-0.2266,  0.4011,  0.7426,  0.0209]])
